// ============================================================================
//
// Copyright (c) 2006-2015, Talend Inc.
//
// This source code has been automatically generated by_Talend Open Studio for Data Integration
// / Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package first.orion_0_1;

import routines.Numeric;
import routines.DataOperation;
import routines.TalendDataGenerator;
import routines.TalendStringUtil;
import routines.TalendString;
import routines.StringHandling;
import routines.Relational;
import routines.TalendDate;
import routines.Mathematical;
import routines.system.*;
import routines.system.api.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;
import java.io.ByteArrayOutputStream;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import java.io.IOException;
import java.util.Comparator;

@SuppressWarnings("unused")

/**
 * Job: orion Purpose: <br>
 * Description: <br>
 * 
 * @author user@talend.com
 * @version 8.0.1.20211109_1610
 * @status
 */
public class orion implements TalendJob {

	protected static void logIgnoredError(String message, Throwable cause) {
		System.err.println(message);
		if (cause != null) {
			cause.printStackTrace();
		}

	}

	public final Object obj = new Object();

	// for transmiting parameters purpose
	private Object valueObject = null;

	public Object getValueObject() {
		return this.valueObject;
	}

	public void setValueObject(Object valueObject) {
		this.valueObject = valueObject;
	}

	private final static String defaultCharset = java.nio.charset.Charset.defaultCharset().name();

	private final static String utf8Charset = "UTF-8";

	// contains type for every context property
	public class PropertiesWithType extends java.util.Properties {
		private static final long serialVersionUID = 1L;
		private java.util.Map<String, String> propertyTypes = new java.util.HashMap<>();

		public PropertiesWithType(java.util.Properties properties) {
			super(properties);
		}

		public PropertiesWithType() {
			super();
		}

		public void setContextType(String key, String type) {
			propertyTypes.put(key, type);
		}

		public String getContextType(String key) {
			return propertyTypes.get(key);
		}
	}

	// create and load default properties
	private java.util.Properties defaultProps = new java.util.Properties();

	// create application properties with default
	public class ContextProperties extends PropertiesWithType {

		private static final long serialVersionUID = 1L;

		public ContextProperties(java.util.Properties properties) {
			super(properties);
		}

		public ContextProperties() {
			super();
		}

		public void synchronizeContext() {

		}

		// if the stored or passed value is "<TALEND_NULL>" string, it mean null
		public String getStringValue(String key) {
			String origin_value = this.getProperty(key);
			if (NULL_VALUE_EXPRESSION_IN_COMMAND_STRING_FOR_CHILD_JOB_ONLY.equals(origin_value)) {
				return null;
			}
			return origin_value;
		}

	}

	protected ContextProperties context = new ContextProperties(); // will be instanciated by MS.

	public ContextProperties getContext() {
		return this.context;
	}

	private final String jobVersion = "0.1";
	private final String jobName = "orion";
	private final String projectName = "FIRST";
	public Integer errorCode = null;
	private String currentComponent = "";

	private final java.util.Map<String, Object> globalMap = new java.util.HashMap<String, Object>();
	private final static java.util.Map<String, Object> junitGlobalMap = new java.util.HashMap<String, Object>();

	private final java.util.Map<String, Long> start_Hash = new java.util.HashMap<String, Long>();
	private final java.util.Map<String, Long> end_Hash = new java.util.HashMap<String, Long>();
	private final java.util.Map<String, Boolean> ok_Hash = new java.util.HashMap<String, Boolean>();
	public final java.util.List<String[]> globalBuffer = new java.util.ArrayList<String[]>();

	private RunStat runStat = new RunStat();

	// OSGi DataSource
	private final static String KEY_DB_DATASOURCES = "KEY_DB_DATASOURCES";

	private final static String KEY_DB_DATASOURCES_RAW = "KEY_DB_DATASOURCES_RAW";

	public void setDataSources(java.util.Map<String, javax.sql.DataSource> dataSources) {
		java.util.Map<String, routines.system.TalendDataSource> talendDataSources = new java.util.HashMap<String, routines.system.TalendDataSource>();
		for (java.util.Map.Entry<String, javax.sql.DataSource> dataSourceEntry : dataSources.entrySet()) {
			talendDataSources.put(dataSourceEntry.getKey(),
					new routines.system.TalendDataSource(dataSourceEntry.getValue()));
		}
		globalMap.put(KEY_DB_DATASOURCES, talendDataSources);
		globalMap.put(KEY_DB_DATASOURCES_RAW, new java.util.HashMap<String, javax.sql.DataSource>(dataSources));
	}

	public void setDataSourceReferences(List serviceReferences) throws Exception {

		java.util.Map<String, routines.system.TalendDataSource> talendDataSources = new java.util.HashMap<String, routines.system.TalendDataSource>();
		java.util.Map<String, javax.sql.DataSource> dataSources = new java.util.HashMap<String, javax.sql.DataSource>();

		for (java.util.Map.Entry<String, javax.sql.DataSource> entry : BundleUtils
				.getServices(serviceReferences, javax.sql.DataSource.class).entrySet()) {
			dataSources.put(entry.getKey(), entry.getValue());
			talendDataSources.put(entry.getKey(), new routines.system.TalendDataSource(entry.getValue()));
		}

		globalMap.put(KEY_DB_DATASOURCES, talendDataSources);
		globalMap.put(KEY_DB_DATASOURCES_RAW, new java.util.HashMap<String, javax.sql.DataSource>(dataSources));
	}

	private final java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
	private final java.io.PrintStream errorMessagePS = new java.io.PrintStream(new java.io.BufferedOutputStream(baos));

	public String getExceptionStackTrace() {
		if ("failure".equals(this.getStatus())) {
			errorMessagePS.flush();
			return baos.toString();
		}
		return null;
	}

	private Exception exception;

	public Exception getException() {
		if ("failure".equals(this.getStatus())) {
			return this.exception;
		}
		return null;
	}

	private class TalendException extends Exception {

		private static final long serialVersionUID = 1L;

		private java.util.Map<String, Object> globalMap = null;
		private Exception e = null;
		private String currentComponent = null;
		private String virtualComponentName = null;

		public void setVirtualComponentName(String virtualComponentName) {
			this.virtualComponentName = virtualComponentName;
		}

		private TalendException(Exception e, String errorComponent, final java.util.Map<String, Object> globalMap) {
			this.currentComponent = errorComponent;
			this.globalMap = globalMap;
			this.e = e;
		}

		public Exception getException() {
			return this.e;
		}

		public String getCurrentComponent() {
			return this.currentComponent;
		}

		public String getExceptionCauseMessage(Exception e) {
			Throwable cause = e;
			String message = null;
			int i = 10;
			while (null != cause && 0 < i--) {
				message = cause.getMessage();
				if (null == message) {
					cause = cause.getCause();
				} else {
					break;
				}
			}
			if (null == message) {
				message = e.getClass().getName();
			}
			return message;
		}

		@Override
		public void printStackTrace() {
			if (!(e instanceof TalendException || e instanceof TDieException)) {
				if (virtualComponentName != null && currentComponent.indexOf(virtualComponentName + "_") == 0) {
					globalMap.put(virtualComponentName + "_ERROR_MESSAGE", getExceptionCauseMessage(e));
				}
				globalMap.put(currentComponent + "_ERROR_MESSAGE", getExceptionCauseMessage(e));
				System.err.println("Exception in component " + currentComponent + " (" + jobName + ")");
			}
			if (!(e instanceof TDieException)) {
				if (e instanceof TalendException) {
					e.printStackTrace();
				} else {
					e.printStackTrace();
					e.printStackTrace(errorMessagePS);
					orion.this.exception = e;
				}
			}
			if (!(e instanceof TalendException)) {
				try {
					for (java.lang.reflect.Method m : this.getClass().getEnclosingClass().getMethods()) {
						if (m.getName().compareTo(currentComponent + "_error") == 0) {
							m.invoke(orion.this, new Object[] { e, currentComponent, globalMap });
							break;
						}
					}

					if (!(e instanceof TDieException)) {
					}
				} catch (Exception e) {
					this.e.printStackTrace();
				}
			}
		}
	}

	public void tDBInput_1_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tDBInput_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tMap_1_error(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tDBInput_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tDBOutput_2_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tDBInput_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tDBInput_2_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tDBInput_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tAdvancedHash_CUSTOMER_Type_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tDBInput_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tDBInput_1_onSubJobError(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public static class CUSTOMER_DIMStruct implements routines.system.IPersistableRow<CUSTOMER_DIMStruct> {
		final static byte[] commonByteArrayLock_FIRST_orion = new byte[0];
		static byte[] commonByteArray_FIRST_orion = new byte[0];
		protected static final int DEFAULT_HASHCODE = 1;
		protected static final int PRIME = 31;
		protected int hashCode = DEFAULT_HASHCODE;
		public boolean hashCodeDirty = true;

		public String loopKey;

		public Double CUSTOMER;

		public Double getCUSTOMER() {
			return this.CUSTOMER;
		}

		public String COUNTRY;

		public String getCOUNTRY() {
			return this.COUNTRY;
		}

		public String GENDER;

		public String getGENDER() {
			return this.GENDER;
		}

		public String GROUP_CUST;

		public String getGROUP_CUST() {
			return this.GROUP_CUST;
		}

		public String TYPE_CUST;

		public String getTYPE_CUST() {
			return this.TYPE_CUST;
		}

		public Integer AGE;

		public Integer getAGE() {
			return this.AGE;
		}

		public String GROUP_AGE;

		public String getGROUP_AGE() {
			return this.GROUP_AGE;
		}

		public String FIRSTNAME;

		public String getFIRSTNAME() {
			return this.FIRSTNAME;
		}

		public String LASTNAME;

		public String getLASTNAME() {
			return this.LASTNAME;
		}

		public java.util.Date BIRTH_DATE;

		public java.util.Date getBIRTH_DATE() {
			return this.BIRTH_DATE;
		}

		@Override
		public int hashCode() {
			if (this.hashCodeDirty) {
				final int prime = PRIME;
				int result = DEFAULT_HASHCODE;

				result = prime * result + ((this.CUSTOMER == null) ? 0 : this.CUSTOMER.hashCode());

				this.hashCode = result;
				this.hashCodeDirty = false;
			}
			return this.hashCode;
		}

		@Override
		public boolean equals(Object obj) {
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			final CUSTOMER_DIMStruct other = (CUSTOMER_DIMStruct) obj;

			if (this.CUSTOMER == null) {
				if (other.CUSTOMER != null)
					return false;

			} else if (!this.CUSTOMER.equals(other.CUSTOMER))

				return false;

			return true;
		}

		public void copyDataTo(CUSTOMER_DIMStruct other) {

			other.CUSTOMER = this.CUSTOMER;
			other.COUNTRY = this.COUNTRY;
			other.GENDER = this.GENDER;
			other.GROUP_CUST = this.GROUP_CUST;
			other.TYPE_CUST = this.TYPE_CUST;
			other.AGE = this.AGE;
			other.GROUP_AGE = this.GROUP_AGE;
			other.FIRSTNAME = this.FIRSTNAME;
			other.LASTNAME = this.LASTNAME;
			other.BIRTH_DATE = this.BIRTH_DATE;

		}

		public void copyKeysDataTo(CUSTOMER_DIMStruct other) {

			other.CUSTOMER = this.CUSTOMER;

		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_FIRST_orion.length) {
					if (length < 1024 && commonByteArray_FIRST_orion.length == 0) {
						commonByteArray_FIRST_orion = new byte[1024];
					} else {
						commonByteArray_FIRST_orion = new byte[2 * length];
					}
				}
				dis.readFully(commonByteArray_FIRST_orion, 0, length);
				strReturn = new String(commonByteArray_FIRST_orion, 0, length, utf8Charset);
			}
			return strReturn;
		}

		private String readString(org.jboss.marshalling.Unmarshaller unmarshaller) throws IOException {
			String strReturn = null;
			int length = 0;
			length = unmarshaller.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_FIRST_orion.length) {
					if (length < 1024 && commonByteArray_FIRST_orion.length == 0) {
						commonByteArray_FIRST_orion = new byte[1024];
					} else {
						commonByteArray_FIRST_orion = new byte[2 * length];
					}
				}
				unmarshaller.readFully(commonByteArray_FIRST_orion, 0, length);
				strReturn = new String(commonByteArray_FIRST_orion, 0, length, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos) throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		private void writeString(String str, org.jboss.marshalling.Marshaller marshaller) throws IOException {
			if (str == null) {
				marshaller.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				marshaller.writeInt(byteArray.length);
				marshaller.write(byteArray);
			}
		}

		private Integer readInteger(ObjectInputStream dis) throws IOException {
			Integer intReturn;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				intReturn = null;
			} else {
				intReturn = dis.readInt();
			}
			return intReturn;
		}

		private Integer readInteger(org.jboss.marshalling.Unmarshaller dis) throws IOException {
			Integer intReturn;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				intReturn = null;
			} else {
				intReturn = dis.readInt();
			}
			return intReturn;
		}

		private void writeInteger(Integer intNum, ObjectOutputStream dos) throws IOException {
			if (intNum == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeInt(intNum);
			}
		}

		private void writeInteger(Integer intNum, org.jboss.marshalling.Marshaller marshaller) throws IOException {
			if (intNum == null) {
				marshaller.writeByte(-1);
			} else {
				marshaller.writeByte(0);
				marshaller.writeInt(intNum);
			}
		}

		private java.util.Date readDate(ObjectInputStream dis) throws IOException {
			java.util.Date dateReturn = null;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				dateReturn = null;
			} else {
				dateReturn = new Date(dis.readLong());
			}
			return dateReturn;
		}

		private java.util.Date readDate(org.jboss.marshalling.Unmarshaller unmarshaller) throws IOException {
			java.util.Date dateReturn = null;
			int length = 0;
			length = unmarshaller.readByte();
			if (length == -1) {
				dateReturn = null;
			} else {
				dateReturn = new Date(unmarshaller.readLong());
			}
			return dateReturn;
		}

		private void writeDate(java.util.Date date1, ObjectOutputStream dos) throws IOException {
			if (date1 == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeLong(date1.getTime());
			}
		}

		private void writeDate(java.util.Date date1, org.jboss.marshalling.Marshaller marshaller) throws IOException {
			if (date1 == null) {
				marshaller.writeByte(-1);
			} else {
				marshaller.writeByte(0);
				marshaller.writeLong(date1.getTime());
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_FIRST_orion) {

				try {

					int length = 0;

					length = dis.readByte();
					if (length == -1) {
						this.CUSTOMER = null;
					} else {
						this.CUSTOMER = dis.readDouble();
					}

					this.COUNTRY = readString(dis);

					this.GENDER = readString(dis);

					this.GROUP_CUST = readString(dis);

					this.TYPE_CUST = readString(dis);

					this.AGE = readInteger(dis);

					this.GROUP_AGE = readString(dis);

					this.FIRSTNAME = readString(dis);

					this.LASTNAME = readString(dis);

					this.BIRTH_DATE = readDate(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void readData(org.jboss.marshalling.Unmarshaller dis) {

			synchronized (commonByteArrayLock_FIRST_orion) {

				try {

					int length = 0;

					length = dis.readByte();
					if (length == -1) {
						this.CUSTOMER = null;
					} else {
						this.CUSTOMER = dis.readDouble();
					}

					this.COUNTRY = readString(dis);

					this.GENDER = readString(dis);

					this.GROUP_CUST = readString(dis);

					this.TYPE_CUST = readString(dis);

					this.AGE = readInteger(dis);

					this.GROUP_AGE = readString(dis);

					this.FIRSTNAME = readString(dis);

					this.LASTNAME = readString(dis);

					this.BIRTH_DATE = readDate(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// Double

				if (this.CUSTOMER == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeDouble(this.CUSTOMER);
				}

				// String

				writeString(this.COUNTRY, dos);

				// String

				writeString(this.GENDER, dos);

				// String

				writeString(this.GROUP_CUST, dos);

				// String

				writeString(this.TYPE_CUST, dos);

				// Integer

				writeInteger(this.AGE, dos);

				// String

				writeString(this.GROUP_AGE, dos);

				// String

				writeString(this.FIRSTNAME, dos);

				// String

				writeString(this.LASTNAME, dos);

				// java.util.Date

				writeDate(this.BIRTH_DATE, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public void writeData(org.jboss.marshalling.Marshaller dos) {
			try {

				// Double

				if (this.CUSTOMER == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeDouble(this.CUSTOMER);
				}

				// String

				writeString(this.COUNTRY, dos);

				// String

				writeString(this.GENDER, dos);

				// String

				writeString(this.GROUP_CUST, dos);

				// String

				writeString(this.TYPE_CUST, dos);

				// Integer

				writeInteger(this.AGE, dos);

				// String

				writeString(this.GROUP_AGE, dos);

				// String

				writeString(this.FIRSTNAME, dos);

				// String

				writeString(this.LASTNAME, dos);

				// java.util.Date

				writeDate(this.BIRTH_DATE, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("CUSTOMER=" + String.valueOf(CUSTOMER));
			sb.append(",COUNTRY=" + COUNTRY);
			sb.append(",GENDER=" + GENDER);
			sb.append(",GROUP_CUST=" + GROUP_CUST);
			sb.append(",TYPE_CUST=" + TYPE_CUST);
			sb.append(",AGE=" + String.valueOf(AGE));
			sb.append(",GROUP_AGE=" + GROUP_AGE);
			sb.append(",FIRSTNAME=" + FIRSTNAME);
			sb.append(",LASTNAME=" + LASTNAME);
			sb.append(",BIRTH_DATE=" + String.valueOf(BIRTH_DATE));
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(CUSTOMER_DIMStruct other) {

			int returnValue = -1;

			returnValue = checkNullsAndCompare(this.CUSTOMER, other.CUSTOMER);
			if (returnValue != 0) {
				return returnValue;
			}

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(), object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public static class CUSTOMERStruct implements routines.system.IPersistableRow<CUSTOMERStruct> {
		final static byte[] commonByteArrayLock_FIRST_orion = new byte[0];
		static byte[] commonByteArray_FIRST_orion = new byte[0];

		public Double CUSTOMER_ID;

		public Double getCUSTOMER_ID() {
			return this.CUSTOMER_ID;
		}

		public String COUNTRY;

		public String getCOUNTRY() {
			return this.COUNTRY;
		}

		public String GENDER;

		public String getGENDER() {
			return this.GENDER;
		}

		public String PERSONAL_ID;

		public String getPERSONAL_ID() {
			return this.PERSONAL_ID;
		}

		public String CUSTOMER_NAME;

		public String getCUSTOMER_NAME() {
			return this.CUSTOMER_NAME;
		}

		public String CUSTOMER_FIRSTNAME;

		public String getCUSTOMER_FIRSTNAME() {
			return this.CUSTOMER_FIRSTNAME;
		}

		public String CUSTOMER_LASTNAME;

		public String getCUSTOMER_LASTNAME() {
			return this.CUSTOMER_LASTNAME;
		}

		public java.util.Date BIRTH_DATE;

		public java.util.Date getBIRTH_DATE() {
			return this.BIRTH_DATE;
		}

		public String CUSTOMER_ADDRESS;

		public String getCUSTOMER_ADDRESS() {
			return this.CUSTOMER_ADDRESS;
		}

		public Double STREET_ID;

		public Double getSTREET_ID() {
			return this.STREET_ID;
		}

		public String STREET_NUMBER;

		public String getSTREET_NUMBER() {
			return this.STREET_NUMBER;
		}

		public Double CUSTOMER_TYPE_ID;

		public Double getCUSTOMER_TYPE_ID() {
			return this.CUSTOMER_TYPE_ID;
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_FIRST_orion.length) {
					if (length < 1024 && commonByteArray_FIRST_orion.length == 0) {
						commonByteArray_FIRST_orion = new byte[1024];
					} else {
						commonByteArray_FIRST_orion = new byte[2 * length];
					}
				}
				dis.readFully(commonByteArray_FIRST_orion, 0, length);
				strReturn = new String(commonByteArray_FIRST_orion, 0, length, utf8Charset);
			}
			return strReturn;
		}

		private String readString(org.jboss.marshalling.Unmarshaller unmarshaller) throws IOException {
			String strReturn = null;
			int length = 0;
			length = unmarshaller.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_FIRST_orion.length) {
					if (length < 1024 && commonByteArray_FIRST_orion.length == 0) {
						commonByteArray_FIRST_orion = new byte[1024];
					} else {
						commonByteArray_FIRST_orion = new byte[2 * length];
					}
				}
				unmarshaller.readFully(commonByteArray_FIRST_orion, 0, length);
				strReturn = new String(commonByteArray_FIRST_orion, 0, length, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos) throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		private void writeString(String str, org.jboss.marshalling.Marshaller marshaller) throws IOException {
			if (str == null) {
				marshaller.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				marshaller.writeInt(byteArray.length);
				marshaller.write(byteArray);
			}
		}

		private java.util.Date readDate(ObjectInputStream dis) throws IOException {
			java.util.Date dateReturn = null;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				dateReturn = null;
			} else {
				dateReturn = new Date(dis.readLong());
			}
			return dateReturn;
		}

		private java.util.Date readDate(org.jboss.marshalling.Unmarshaller unmarshaller) throws IOException {
			java.util.Date dateReturn = null;
			int length = 0;
			length = unmarshaller.readByte();
			if (length == -1) {
				dateReturn = null;
			} else {
				dateReturn = new Date(unmarshaller.readLong());
			}
			return dateReturn;
		}

		private void writeDate(java.util.Date date1, ObjectOutputStream dos) throws IOException {
			if (date1 == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeLong(date1.getTime());
			}
		}

		private void writeDate(java.util.Date date1, org.jboss.marshalling.Marshaller marshaller) throws IOException {
			if (date1 == null) {
				marshaller.writeByte(-1);
			} else {
				marshaller.writeByte(0);
				marshaller.writeLong(date1.getTime());
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_FIRST_orion) {

				try {

					int length = 0;

					length = dis.readByte();
					if (length == -1) {
						this.CUSTOMER_ID = null;
					} else {
						this.CUSTOMER_ID = dis.readDouble();
					}

					this.COUNTRY = readString(dis);

					this.GENDER = readString(dis);

					this.PERSONAL_ID = readString(dis);

					this.CUSTOMER_NAME = readString(dis);

					this.CUSTOMER_FIRSTNAME = readString(dis);

					this.CUSTOMER_LASTNAME = readString(dis);

					this.BIRTH_DATE = readDate(dis);

					this.CUSTOMER_ADDRESS = readString(dis);

					length = dis.readByte();
					if (length == -1) {
						this.STREET_ID = null;
					} else {
						this.STREET_ID = dis.readDouble();
					}

					this.STREET_NUMBER = readString(dis);

					length = dis.readByte();
					if (length == -1) {
						this.CUSTOMER_TYPE_ID = null;
					} else {
						this.CUSTOMER_TYPE_ID = dis.readDouble();
					}

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void readData(org.jboss.marshalling.Unmarshaller dis) {

			synchronized (commonByteArrayLock_FIRST_orion) {

				try {

					int length = 0;

					length = dis.readByte();
					if (length == -1) {
						this.CUSTOMER_ID = null;
					} else {
						this.CUSTOMER_ID = dis.readDouble();
					}

					this.COUNTRY = readString(dis);

					this.GENDER = readString(dis);

					this.PERSONAL_ID = readString(dis);

					this.CUSTOMER_NAME = readString(dis);

					this.CUSTOMER_FIRSTNAME = readString(dis);

					this.CUSTOMER_LASTNAME = readString(dis);

					this.BIRTH_DATE = readDate(dis);

					this.CUSTOMER_ADDRESS = readString(dis);

					length = dis.readByte();
					if (length == -1) {
						this.STREET_ID = null;
					} else {
						this.STREET_ID = dis.readDouble();
					}

					this.STREET_NUMBER = readString(dis);

					length = dis.readByte();
					if (length == -1) {
						this.CUSTOMER_TYPE_ID = null;
					} else {
						this.CUSTOMER_TYPE_ID = dis.readDouble();
					}

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// Double

				if (this.CUSTOMER_ID == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeDouble(this.CUSTOMER_ID);
				}

				// String

				writeString(this.COUNTRY, dos);

				// String

				writeString(this.GENDER, dos);

				// String

				writeString(this.PERSONAL_ID, dos);

				// String

				writeString(this.CUSTOMER_NAME, dos);

				// String

				writeString(this.CUSTOMER_FIRSTNAME, dos);

				// String

				writeString(this.CUSTOMER_LASTNAME, dos);

				// java.util.Date

				writeDate(this.BIRTH_DATE, dos);

				// String

				writeString(this.CUSTOMER_ADDRESS, dos);

				// Double

				if (this.STREET_ID == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeDouble(this.STREET_ID);
				}

				// String

				writeString(this.STREET_NUMBER, dos);

				// Double

				if (this.CUSTOMER_TYPE_ID == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeDouble(this.CUSTOMER_TYPE_ID);
				}

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public void writeData(org.jboss.marshalling.Marshaller dos) {
			try {

				// Double

				if (this.CUSTOMER_ID == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeDouble(this.CUSTOMER_ID);
				}

				// String

				writeString(this.COUNTRY, dos);

				// String

				writeString(this.GENDER, dos);

				// String

				writeString(this.PERSONAL_ID, dos);

				// String

				writeString(this.CUSTOMER_NAME, dos);

				// String

				writeString(this.CUSTOMER_FIRSTNAME, dos);

				// String

				writeString(this.CUSTOMER_LASTNAME, dos);

				// java.util.Date

				writeDate(this.BIRTH_DATE, dos);

				// String

				writeString(this.CUSTOMER_ADDRESS, dos);

				// Double

				if (this.STREET_ID == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeDouble(this.STREET_ID);
				}

				// String

				writeString(this.STREET_NUMBER, dos);

				// Double

				if (this.CUSTOMER_TYPE_ID == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeDouble(this.CUSTOMER_TYPE_ID);
				}

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("CUSTOMER_ID=" + String.valueOf(CUSTOMER_ID));
			sb.append(",COUNTRY=" + COUNTRY);
			sb.append(",GENDER=" + GENDER);
			sb.append(",PERSONAL_ID=" + PERSONAL_ID);
			sb.append(",CUSTOMER_NAME=" + CUSTOMER_NAME);
			sb.append(",CUSTOMER_FIRSTNAME=" + CUSTOMER_FIRSTNAME);
			sb.append(",CUSTOMER_LASTNAME=" + CUSTOMER_LASTNAME);
			sb.append(",BIRTH_DATE=" + String.valueOf(BIRTH_DATE));
			sb.append(",CUSTOMER_ADDRESS=" + CUSTOMER_ADDRESS);
			sb.append(",STREET_ID=" + String.valueOf(STREET_ID));
			sb.append(",STREET_NUMBER=" + STREET_NUMBER);
			sb.append(",CUSTOMER_TYPE_ID=" + String.valueOf(CUSTOMER_TYPE_ID));
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(CUSTOMERStruct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(), object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public static class after_tDBInput_1Struct implements routines.system.IPersistableRow<after_tDBInput_1Struct> {
		final static byte[] commonByteArrayLock_FIRST_orion = new byte[0];
		static byte[] commonByteArray_FIRST_orion = new byte[0];

		public Double CUSTOMER_ID;

		public Double getCUSTOMER_ID() {
			return this.CUSTOMER_ID;
		}

		public String COUNTRY;

		public String getCOUNTRY() {
			return this.COUNTRY;
		}

		public String GENDER;

		public String getGENDER() {
			return this.GENDER;
		}

		public String PERSONAL_ID;

		public String getPERSONAL_ID() {
			return this.PERSONAL_ID;
		}

		public String CUSTOMER_NAME;

		public String getCUSTOMER_NAME() {
			return this.CUSTOMER_NAME;
		}

		public String CUSTOMER_FIRSTNAME;

		public String getCUSTOMER_FIRSTNAME() {
			return this.CUSTOMER_FIRSTNAME;
		}

		public String CUSTOMER_LASTNAME;

		public String getCUSTOMER_LASTNAME() {
			return this.CUSTOMER_LASTNAME;
		}

		public java.util.Date BIRTH_DATE;

		public java.util.Date getBIRTH_DATE() {
			return this.BIRTH_DATE;
		}

		public String CUSTOMER_ADDRESS;

		public String getCUSTOMER_ADDRESS() {
			return this.CUSTOMER_ADDRESS;
		}

		public Double STREET_ID;

		public Double getSTREET_ID() {
			return this.STREET_ID;
		}

		public String STREET_NUMBER;

		public String getSTREET_NUMBER() {
			return this.STREET_NUMBER;
		}

		public Double CUSTOMER_TYPE_ID;

		public Double getCUSTOMER_TYPE_ID() {
			return this.CUSTOMER_TYPE_ID;
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_FIRST_orion.length) {
					if (length < 1024 && commonByteArray_FIRST_orion.length == 0) {
						commonByteArray_FIRST_orion = new byte[1024];
					} else {
						commonByteArray_FIRST_orion = new byte[2 * length];
					}
				}
				dis.readFully(commonByteArray_FIRST_orion, 0, length);
				strReturn = new String(commonByteArray_FIRST_orion, 0, length, utf8Charset);
			}
			return strReturn;
		}

		private String readString(org.jboss.marshalling.Unmarshaller unmarshaller) throws IOException {
			String strReturn = null;
			int length = 0;
			length = unmarshaller.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_FIRST_orion.length) {
					if (length < 1024 && commonByteArray_FIRST_orion.length == 0) {
						commonByteArray_FIRST_orion = new byte[1024];
					} else {
						commonByteArray_FIRST_orion = new byte[2 * length];
					}
				}
				unmarshaller.readFully(commonByteArray_FIRST_orion, 0, length);
				strReturn = new String(commonByteArray_FIRST_orion, 0, length, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos) throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		private void writeString(String str, org.jboss.marshalling.Marshaller marshaller) throws IOException {
			if (str == null) {
				marshaller.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				marshaller.writeInt(byteArray.length);
				marshaller.write(byteArray);
			}
		}

		private java.util.Date readDate(ObjectInputStream dis) throws IOException {
			java.util.Date dateReturn = null;
			int length = 0;
			length = dis.readByte();
			if (length == -1) {
				dateReturn = null;
			} else {
				dateReturn = new Date(dis.readLong());
			}
			return dateReturn;
		}

		private java.util.Date readDate(org.jboss.marshalling.Unmarshaller unmarshaller) throws IOException {
			java.util.Date dateReturn = null;
			int length = 0;
			length = unmarshaller.readByte();
			if (length == -1) {
				dateReturn = null;
			} else {
				dateReturn = new Date(unmarshaller.readLong());
			}
			return dateReturn;
		}

		private void writeDate(java.util.Date date1, ObjectOutputStream dos) throws IOException {
			if (date1 == null) {
				dos.writeByte(-1);
			} else {
				dos.writeByte(0);
				dos.writeLong(date1.getTime());
			}
		}

		private void writeDate(java.util.Date date1, org.jboss.marshalling.Marshaller marshaller) throws IOException {
			if (date1 == null) {
				marshaller.writeByte(-1);
			} else {
				marshaller.writeByte(0);
				marshaller.writeLong(date1.getTime());
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_FIRST_orion) {

				try {

					int length = 0;

					length = dis.readByte();
					if (length == -1) {
						this.CUSTOMER_ID = null;
					} else {
						this.CUSTOMER_ID = dis.readDouble();
					}

					this.COUNTRY = readString(dis);

					this.GENDER = readString(dis);

					this.PERSONAL_ID = readString(dis);

					this.CUSTOMER_NAME = readString(dis);

					this.CUSTOMER_FIRSTNAME = readString(dis);

					this.CUSTOMER_LASTNAME = readString(dis);

					this.BIRTH_DATE = readDate(dis);

					this.CUSTOMER_ADDRESS = readString(dis);

					length = dis.readByte();
					if (length == -1) {
						this.STREET_ID = null;
					} else {
						this.STREET_ID = dis.readDouble();
					}

					this.STREET_NUMBER = readString(dis);

					length = dis.readByte();
					if (length == -1) {
						this.CUSTOMER_TYPE_ID = null;
					} else {
						this.CUSTOMER_TYPE_ID = dis.readDouble();
					}

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void readData(org.jboss.marshalling.Unmarshaller dis) {

			synchronized (commonByteArrayLock_FIRST_orion) {

				try {

					int length = 0;

					length = dis.readByte();
					if (length == -1) {
						this.CUSTOMER_ID = null;
					} else {
						this.CUSTOMER_ID = dis.readDouble();
					}

					this.COUNTRY = readString(dis);

					this.GENDER = readString(dis);

					this.PERSONAL_ID = readString(dis);

					this.CUSTOMER_NAME = readString(dis);

					this.CUSTOMER_FIRSTNAME = readString(dis);

					this.CUSTOMER_LASTNAME = readString(dis);

					this.BIRTH_DATE = readDate(dis);

					this.CUSTOMER_ADDRESS = readString(dis);

					length = dis.readByte();
					if (length == -1) {
						this.STREET_ID = null;
					} else {
						this.STREET_ID = dis.readDouble();
					}

					this.STREET_NUMBER = readString(dis);

					length = dis.readByte();
					if (length == -1) {
						this.CUSTOMER_TYPE_ID = null;
					} else {
						this.CUSTOMER_TYPE_ID = dis.readDouble();
					}

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// Double

				if (this.CUSTOMER_ID == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeDouble(this.CUSTOMER_ID);
				}

				// String

				writeString(this.COUNTRY, dos);

				// String

				writeString(this.GENDER, dos);

				// String

				writeString(this.PERSONAL_ID, dos);

				// String

				writeString(this.CUSTOMER_NAME, dos);

				// String

				writeString(this.CUSTOMER_FIRSTNAME, dos);

				// String

				writeString(this.CUSTOMER_LASTNAME, dos);

				// java.util.Date

				writeDate(this.BIRTH_DATE, dos);

				// String

				writeString(this.CUSTOMER_ADDRESS, dos);

				// Double

				if (this.STREET_ID == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeDouble(this.STREET_ID);
				}

				// String

				writeString(this.STREET_NUMBER, dos);

				// Double

				if (this.CUSTOMER_TYPE_ID == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeDouble(this.CUSTOMER_TYPE_ID);
				}

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public void writeData(org.jboss.marshalling.Marshaller dos) {
			try {

				// Double

				if (this.CUSTOMER_ID == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeDouble(this.CUSTOMER_ID);
				}

				// String

				writeString(this.COUNTRY, dos);

				// String

				writeString(this.GENDER, dos);

				// String

				writeString(this.PERSONAL_ID, dos);

				// String

				writeString(this.CUSTOMER_NAME, dos);

				// String

				writeString(this.CUSTOMER_FIRSTNAME, dos);

				// String

				writeString(this.CUSTOMER_LASTNAME, dos);

				// java.util.Date

				writeDate(this.BIRTH_DATE, dos);

				// String

				writeString(this.CUSTOMER_ADDRESS, dos);

				// Double

				if (this.STREET_ID == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeDouble(this.STREET_ID);
				}

				// String

				writeString(this.STREET_NUMBER, dos);

				// Double

				if (this.CUSTOMER_TYPE_ID == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeDouble(this.CUSTOMER_TYPE_ID);
				}

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("CUSTOMER_ID=" + String.valueOf(CUSTOMER_ID));
			sb.append(",COUNTRY=" + COUNTRY);
			sb.append(",GENDER=" + GENDER);
			sb.append(",PERSONAL_ID=" + PERSONAL_ID);
			sb.append(",CUSTOMER_NAME=" + CUSTOMER_NAME);
			sb.append(",CUSTOMER_FIRSTNAME=" + CUSTOMER_FIRSTNAME);
			sb.append(",CUSTOMER_LASTNAME=" + CUSTOMER_LASTNAME);
			sb.append(",BIRTH_DATE=" + String.valueOf(BIRTH_DATE));
			sb.append(",CUSTOMER_ADDRESS=" + CUSTOMER_ADDRESS);
			sb.append(",STREET_ID=" + String.valueOf(STREET_ID));
			sb.append(",STREET_NUMBER=" + STREET_NUMBER);
			sb.append(",CUSTOMER_TYPE_ID=" + String.valueOf(CUSTOMER_TYPE_ID));
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(after_tDBInput_1Struct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(), object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public void tDBInput_1Process(final java.util.Map<String, Object> globalMap) throws TalendException {
		globalMap.put("tDBInput_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";

		String currentComponent = "";
		java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

		try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { // start the resume
				globalResumeTicket = true;

				tDBInput_2Process(globalMap);

				CUSTOMERStruct CUSTOMER = new CUSTOMERStruct();
				CUSTOMER_DIMStruct CUSTOMER_DIM = new CUSTOMER_DIMStruct();

				/**
				 * [tDBOutput_2 begin ] start
				 */

				ok_Hash.put("tDBOutput_2", false);
				start_Hash.put("tDBOutput_2", System.currentTimeMillis());

				currentComponent = "tDBOutput_2";

				if (execStat) {
					runStat.updateStatOnConnection(resourceMap, iterateId, 0, 0, "CUSTOMER_DIM");
				}

				int tos_count_tDBOutput_2 = 0;

				int nb_line_tDBOutput_2 = 0;
				int nb_line_update_tDBOutput_2 = 0;
				int nb_line_inserted_tDBOutput_2 = 0;
				int nb_line_deleted_tDBOutput_2 = 0;
				int nb_line_rejected_tDBOutput_2 = 0;

				int deletedCount_tDBOutput_2 = 0;
				int updatedCount_tDBOutput_2 = 0;
				int insertedCount_tDBOutput_2 = 0;
				int rowsToCommitCount_tDBOutput_2 = 0;
				int rejectedCount_tDBOutput_2 = 0;

				String tableName_tDBOutput_2 = "customer_id";
				boolean whetherReject_tDBOutput_2 = false;

				java.util.Calendar calendar_tDBOutput_2 = java.util.Calendar.getInstance();
				calendar_tDBOutput_2.set(1, 0, 1, 0, 0, 0);
				long year1_tDBOutput_2 = calendar_tDBOutput_2.getTime().getTime();
				calendar_tDBOutput_2.set(10000, 0, 1, 0, 0, 0);
				long year10000_tDBOutput_2 = calendar_tDBOutput_2.getTime().getTime();
				long date_tDBOutput_2;

				java.sql.Connection conn_tDBOutput_2 = null;

				String url_tDBOutput_2 = "jdbc:mysql://" + "localhost" + ":" + "3306" + "/" + "talend" + "?"
						+ "rewriteBatchedStatements=true";

				String driverClass_tDBOutput_2 = "com.mysql.cj.jdbc.Driver";

				String dbUser_tDBOutput_2 = "root";

				final String decryptedPassword_tDBOutput_2 = routines.system.PasswordEncryptUtil
						.decryptPassword("enc:routine.encryption.key.v1:SoaL1xoCnthgrYfbFLcNiRbVtyYXsb/E4CfV6pxnZs0=");

				String dbPwd_tDBOutput_2 = decryptedPassword_tDBOutput_2;
				java.lang.Class.forName(driverClass_tDBOutput_2);

				conn_tDBOutput_2 = java.sql.DriverManager.getConnection(url_tDBOutput_2, dbUser_tDBOutput_2,
						dbPwd_tDBOutput_2);

				resourceMap.put("conn_tDBOutput_2", conn_tDBOutput_2);
				conn_tDBOutput_2.setAutoCommit(false);
				int commitEvery_tDBOutput_2 = 10000;
				int commitCounter_tDBOutput_2 = 0;

				int count_tDBOutput_2 = 0;

				String insert_tDBOutput_2 = "INSERT INTO `" + "customer_id"
						+ "` (`CUSTOMER`,`COUNTRY`,`GENDER`,`GROUP_CUST`,`TYPE_CUST`,`AGE`,`GROUP_AGE`,`FIRSTNAME`,`LASTNAME`,`BIRTH_DATE`) VALUES (?,?,?,?,?,?,?,?,?,?)";
				int batchSize_tDBOutput_2 = 100;
				int batchSizeCounter_tDBOutput_2 = 0;

				java.sql.PreparedStatement pstmt_tDBOutput_2 = conn_tDBOutput_2.prepareStatement(insert_tDBOutput_2);
				resourceMap.put("pstmt_tDBOutput_2", pstmt_tDBOutput_2);

				/**
				 * [tDBOutput_2 begin ] stop
				 */

				/**
				 * [tMap_1 begin ] start
				 */

				ok_Hash.put("tMap_1", false);
				start_Hash.put("tMap_1", System.currentTimeMillis());

				currentComponent = "tMap_1";

				if (execStat) {
					runStat.updateStatOnConnection(resourceMap, iterateId, 0, 0, "CUSTOMER");
				}

				int tos_count_tMap_1 = 0;

// ###############################
// # Lookup's keys initialization

				org.talend.designer.components.lookup.memory.AdvancedMemoryLookup<CUSTOMER_TypeStruct> tHash_Lookup_CUSTOMER_Type = (org.talend.designer.components.lookup.memory.AdvancedMemoryLookup<CUSTOMER_TypeStruct>) ((org.talend.designer.components.lookup.memory.AdvancedMemoryLookup<CUSTOMER_TypeStruct>) globalMap
						.get("tHash_Lookup_CUSTOMER_Type"));

				CUSTOMER_TypeStruct CUSTOMER_TypeHashKey = new CUSTOMER_TypeStruct();
				CUSTOMER_TypeStruct CUSTOMER_TypeDefault = new CUSTOMER_TypeStruct();
// ###############################        

// ###############################
// # Vars initialization
				class Var__tMap_1__Struct {
					Integer AGE;
				}
				Var__tMap_1__Struct Var__tMap_1 = new Var__tMap_1__Struct();
// ###############################

// ###############################
// # Outputs initialization
				CUSTOMER_DIMStruct CUSTOMER_DIM_tmp = new CUSTOMER_DIMStruct();
// ###############################

				/**
				 * [tMap_1 begin ] stop
				 */

				/**
				 * [tDBInput_1 begin ] start
				 */

				ok_Hash.put("tDBInput_1", false);
				start_Hash.put("tDBInput_1", System.currentTimeMillis());

				currentComponent = "tDBInput_1";

				int tos_count_tDBInput_1 = 0;

				int nb_line_tDBInput_1 = 0;
				java.sql.Connection conn_tDBInput_1 = null;
				String driverClass_tDBInput_1 = "net.ucanaccess.jdbc.UcanaccessDriver";
				java.lang.Class.forName(driverClass_tDBInput_1);

				String url_tDBInput_1 = "jdbc:ucanaccess://" + "C:/Users/bechi/Downloads/orion.mdb"
						+ ";jackcessOpener=org.talend.ucanaccess.encrypt.CryptCodecOpener;singleConnection=true";
				String dbUser_tDBInput_1 = "";

				final String decryptedPassword_tDBInput_1 = routines.system.PasswordEncryptUtil
						.decryptPassword("enc:routine.encryption.key.v1:9rnmoR1//RmiVTLQfYUK9/Q6VPW84AYltFxr7g==");

				String dbPwd_tDBInput_1 = decryptedPassword_tDBInput_1;

				String atnParams_tDBInput_1 = "jackcessOpener=org.talend.ucanaccess.encrypt.CryptCodecOpener;memory=false";
				atnParams_tDBInput_1 = atnParams_tDBInput_1.replaceAll("&", "\n");
				java.util.Properties atnParamsPrope_tDBInput_1 = new java.util.Properties();
				atnParamsPrope_tDBInput_1.put("user", dbUser_tDBInput_1);
				atnParamsPrope_tDBInput_1.put("password", dbPwd_tDBInput_1);
				atnParamsPrope_tDBInput_1.load(new java.io.ByteArrayInputStream(atnParams_tDBInput_1.getBytes()));
				conn_tDBInput_1 = java.sql.DriverManager.getConnection(url_tDBInput_1, atnParamsPrope_tDBInput_1);

				java.sql.Statement stmt_tDBInput_1 = conn_tDBInput_1.createStatement();

				String dbquery_tDBInput_1 = "SELECT \n  CUSTOMER.CUSTOMER_ID, \n  CUSTOMER.COUNTRY, \n  CUSTOMER.GENDER, \n  CUSTOMER.PERSONAL_ID, \n  CUSTOMER.CUSTOMER_"
						+ "NAME, \n  CUSTOMER.CUSTOMER_FIRSTNAME, \n  CUSTOMER.CUSTOMER_LASTNAME, \n  CUSTOMER.BIRTH_DATE, \n  CUSTOMER.CUSTOMER_ADDRES"
						+ "S, \n  CUSTOMER.STREET_ID, \n  CUSTOMER.STREET_NUMBER, \n  CUSTOMER.CUSTOMER_TYPE_ID\nFROM CUSTOMER";

				globalMap.put("tDBInput_1_QUERY", dbquery_tDBInput_1);
				java.sql.ResultSet rs_tDBInput_1 = null;

				try {
					rs_tDBInput_1 = stmt_tDBInput_1.executeQuery(dbquery_tDBInput_1);
					java.sql.ResultSetMetaData rsmd_tDBInput_1 = rs_tDBInput_1.getMetaData();
					int colQtyInRs_tDBInput_1 = rsmd_tDBInput_1.getColumnCount();

					String tmpContent_tDBInput_1 = null;

					while (rs_tDBInput_1.next()) {
						nb_line_tDBInput_1++;

						if (colQtyInRs_tDBInput_1 < 1) {
							CUSTOMER.CUSTOMER_ID = null;
						} else {

							CUSTOMER.CUSTOMER_ID = rs_tDBInput_1.getDouble(1);
							if (rs_tDBInput_1.wasNull()) {
								CUSTOMER.CUSTOMER_ID = null;
							}
						}
						if (colQtyInRs_tDBInput_1 < 2) {
							CUSTOMER.COUNTRY = null;
						} else {

							CUSTOMER.COUNTRY = routines.system.JDBCUtil.getString(rs_tDBInput_1, 2, false);
						}
						if (colQtyInRs_tDBInput_1 < 3) {
							CUSTOMER.GENDER = null;
						} else {

							CUSTOMER.GENDER = routines.system.JDBCUtil.getString(rs_tDBInput_1, 3, false);
						}
						if (colQtyInRs_tDBInput_1 < 4) {
							CUSTOMER.PERSONAL_ID = null;
						} else {

							CUSTOMER.PERSONAL_ID = routines.system.JDBCUtil.getString(rs_tDBInput_1, 4, false);
						}
						if (colQtyInRs_tDBInput_1 < 5) {
							CUSTOMER.CUSTOMER_NAME = null;
						} else {

							CUSTOMER.CUSTOMER_NAME = routines.system.JDBCUtil.getString(rs_tDBInput_1, 5, false);
						}
						if (colQtyInRs_tDBInput_1 < 6) {
							CUSTOMER.CUSTOMER_FIRSTNAME = null;
						} else {

							CUSTOMER.CUSTOMER_FIRSTNAME = routines.system.JDBCUtil.getString(rs_tDBInput_1, 6, false);
						}
						if (colQtyInRs_tDBInput_1 < 7) {
							CUSTOMER.CUSTOMER_LASTNAME = null;
						} else {

							CUSTOMER.CUSTOMER_LASTNAME = routines.system.JDBCUtil.getString(rs_tDBInput_1, 7, false);
						}
						if (colQtyInRs_tDBInput_1 < 8) {
							CUSTOMER.BIRTH_DATE = null;
						} else {

							java.sql.Timestamp timestamp_tDBInput_1 = rs_tDBInput_1.getTimestamp(8);
							if (timestamp_tDBInput_1 != null) {
								CUSTOMER.BIRTH_DATE = new java.util.Date(timestamp_tDBInput_1.getTime());
							} else {
								CUSTOMER.BIRTH_DATE = null;
							}
						}
						if (colQtyInRs_tDBInput_1 < 9) {
							CUSTOMER.CUSTOMER_ADDRESS = null;
						} else {

							CUSTOMER.CUSTOMER_ADDRESS = routines.system.JDBCUtil.getString(rs_tDBInput_1, 9, false);
						}
						if (colQtyInRs_tDBInput_1 < 10) {
							CUSTOMER.STREET_ID = null;
						} else {

							CUSTOMER.STREET_ID = rs_tDBInput_1.getDouble(10);
							if (rs_tDBInput_1.wasNull()) {
								CUSTOMER.STREET_ID = null;
							}
						}
						if (colQtyInRs_tDBInput_1 < 11) {
							CUSTOMER.STREET_NUMBER = null;
						} else {

							CUSTOMER.STREET_NUMBER = routines.system.JDBCUtil.getString(rs_tDBInput_1, 11, false);
						}
						if (colQtyInRs_tDBInput_1 < 12) {
							CUSTOMER.CUSTOMER_TYPE_ID = null;
						} else {

							CUSTOMER.CUSTOMER_TYPE_ID = rs_tDBInput_1.getDouble(12);
							if (rs_tDBInput_1.wasNull()) {
								CUSTOMER.CUSTOMER_TYPE_ID = null;
							}
						}

						/**
						 * [tDBInput_1 begin ] stop
						 */

						/**
						 * [tDBInput_1 main ] start
						 */

						currentComponent = "tDBInput_1";

						tos_count_tDBInput_1++;

						/**
						 * [tDBInput_1 main ] stop
						 */

						/**
						 * [tDBInput_1 process_data_begin ] start
						 */

						currentComponent = "tDBInput_1";

						/**
						 * [tDBInput_1 process_data_begin ] stop
						 */

						/**
						 * [tMap_1 main ] start
						 */

						currentComponent = "tMap_1";

						if (execStat) {
							runStat.updateStatOnConnection(iterateId, 1, 1

									, "CUSTOMER"

							);
						}

						boolean hasCasePrimitiveKeyWithNull_tMap_1 = false;

						// ###############################
						// # Input tables (lookups)
						boolean rejectedInnerJoin_tMap_1 = false;
						boolean mainRowRejected_tMap_1 = false;

						///////////////////////////////////////////////
						// Starting Lookup Table "CUSTOMER_Type"
						///////////////////////////////////////////////

						boolean forceLoopCUSTOMER_Type = false;

						CUSTOMER_TypeStruct CUSTOMER_TypeObjectFromLookup = null;

						if (!rejectedInnerJoin_tMap_1) { // G_TM_M_020

							hasCasePrimitiveKeyWithNull_tMap_1 = false;

							CUSTOMER_TypeHashKey.CUSTOMER_TYPE_ID = CUSTOMER.CUSTOMER_TYPE_ID;

							CUSTOMER_TypeHashKey.hashCodeDirty = true;

							tHash_Lookup_CUSTOMER_Type.lookup(CUSTOMER_TypeHashKey);

						} // G_TM_M_020

						if (tHash_Lookup_CUSTOMER_Type != null
								&& tHash_Lookup_CUSTOMER_Type.getCount(CUSTOMER_TypeHashKey) > 1) { // G 071

							// System.out.println("WARNING: UNIQUE MATCH is configured for the lookup
							// 'CUSTOMER_Type' and it contains more one result from keys :
							// CUSTOMER_Type.CUSTOMER_TYPE_ID = '" + CUSTOMER_TypeHashKey.CUSTOMER_TYPE_ID +
							// "'");
						} // G 071

						CUSTOMER_TypeStruct CUSTOMER_Type = null;

						CUSTOMER_TypeStruct fromLookup_CUSTOMER_Type = null;
						CUSTOMER_Type = CUSTOMER_TypeDefault;

						if (tHash_Lookup_CUSTOMER_Type != null && tHash_Lookup_CUSTOMER_Type.hasNext()) { // G 099

							fromLookup_CUSTOMER_Type = tHash_Lookup_CUSTOMER_Type.next();

						} // G 099

						if (fromLookup_CUSTOMER_Type != null) {
							CUSTOMER_Type = fromLookup_CUSTOMER_Type;
						}

						// ###############################
						{ // start of Var scope

							// ###############################
							// # Vars tables

							Var__tMap_1__Struct Var = Var__tMap_1;
							Var.AGE = Mathematical.INT(TalendDate.formatDate("yyyy", TalendDate.getCurrentDate()))
									- Mathematical.INT(TalendDate.formatDate("yyyy", CUSTOMER.BIRTH_DATE));// ###############################
							// ###############################
							// # Output tables

							CUSTOMER_DIM = null;

// # Output table : 'CUSTOMER_DIM'
							CUSTOMER_DIM_tmp.CUSTOMER = CUSTOMER.CUSTOMER_ID;
							CUSTOMER_DIM_tmp.COUNTRY = CUSTOMER.COUNTRY;
							CUSTOMER_DIM_tmp.GENDER = CUSTOMER.GENDER;
							CUSTOMER_DIM_tmp.GROUP_CUST = CUSTOMER_Type.CUSTOMER_GROUP;
							CUSTOMER_DIM_tmp.TYPE_CUST = CUSTOMER_Type.CUSTOMER_TYPE;
							CUSTOMER_DIM_tmp.AGE = Var.AGE;
							CUSTOMER_DIM_tmp.GROUP_AGE = Var.AGE < 30 ? "<30 years"
									: Var.AGE < 46 ? "30-45 years"
											: Var.AGE < 61 ? "46-60 years" : Var.AGE < 76 ? "61-75 years" : ">75 years";
							CUSTOMER_DIM_tmp.FIRSTNAME = CUSTOMER.CUSTOMER_FIRSTNAME;
							CUSTOMER_DIM_tmp.LASTNAME = CUSTOMER.CUSTOMER_LASTNAME;
							CUSTOMER_DIM_tmp.BIRTH_DATE = CUSTOMER.BIRTH_DATE;
							CUSTOMER_DIM = CUSTOMER_DIM_tmp;
// ###############################

						} // end of Var scope

						rejectedInnerJoin_tMap_1 = false;

						tos_count_tMap_1++;

						/**
						 * [tMap_1 main ] stop
						 */

						/**
						 * [tMap_1 process_data_begin ] start
						 */

						currentComponent = "tMap_1";

						/**
						 * [tMap_1 process_data_begin ] stop
						 */
// Start of branch "CUSTOMER_DIM"
						if (CUSTOMER_DIM != null) {

							/**
							 * [tDBOutput_2 main ] start
							 */

							currentComponent = "tDBOutput_2";

							if (execStat) {
								runStat.updateStatOnConnection(iterateId, 1, 1

										, "CUSTOMER_DIM"

								);
							}

							whetherReject_tDBOutput_2 = false;
							if (CUSTOMER_DIM.CUSTOMER == null) {
								pstmt_tDBOutput_2.setNull(1, java.sql.Types.DOUBLE);
							} else {
								pstmt_tDBOutput_2.setDouble(1, CUSTOMER_DIM.CUSTOMER);
							}

							if (CUSTOMER_DIM.COUNTRY == null) {
								pstmt_tDBOutput_2.setNull(2, java.sql.Types.VARCHAR);
							} else {
								pstmt_tDBOutput_2.setString(2, CUSTOMER_DIM.COUNTRY);
							}

							if (CUSTOMER_DIM.GENDER == null) {
								pstmt_tDBOutput_2.setNull(3, java.sql.Types.VARCHAR);
							} else {
								pstmt_tDBOutput_2.setString(3, CUSTOMER_DIM.GENDER);
							}

							if (CUSTOMER_DIM.GROUP_CUST == null) {
								pstmt_tDBOutput_2.setNull(4, java.sql.Types.VARCHAR);
							} else {
								pstmt_tDBOutput_2.setString(4, CUSTOMER_DIM.GROUP_CUST);
							}

							if (CUSTOMER_DIM.TYPE_CUST == null) {
								pstmt_tDBOutput_2.setNull(5, java.sql.Types.VARCHAR);
							} else {
								pstmt_tDBOutput_2.setString(5, CUSTOMER_DIM.TYPE_CUST);
							}

							if (CUSTOMER_DIM.AGE == null) {
								pstmt_tDBOutput_2.setNull(6, java.sql.Types.INTEGER);
							} else {
								pstmt_tDBOutput_2.setInt(6, CUSTOMER_DIM.AGE);
							}

							if (CUSTOMER_DIM.GROUP_AGE == null) {
								pstmt_tDBOutput_2.setNull(7, java.sql.Types.VARCHAR);
							} else {
								pstmt_tDBOutput_2.setString(7, CUSTOMER_DIM.GROUP_AGE);
							}

							if (CUSTOMER_DIM.FIRSTNAME == null) {
								pstmt_tDBOutput_2.setNull(8, java.sql.Types.VARCHAR);
							} else {
								pstmt_tDBOutput_2.setString(8, CUSTOMER_DIM.FIRSTNAME);
							}

							if (CUSTOMER_DIM.LASTNAME == null) {
								pstmt_tDBOutput_2.setNull(9, java.sql.Types.VARCHAR);
							} else {
								pstmt_tDBOutput_2.setString(9, CUSTOMER_DIM.LASTNAME);
							}

							if (CUSTOMER_DIM.BIRTH_DATE != null) {
								date_tDBOutput_2 = CUSTOMER_DIM.BIRTH_DATE.getTime();
								if (date_tDBOutput_2 < year1_tDBOutput_2 || date_tDBOutput_2 >= year10000_tDBOutput_2) {
									pstmt_tDBOutput_2.setString(10, "0000-00-00 00:00:00");
								} else {
									pstmt_tDBOutput_2.setTimestamp(10, new java.sql.Timestamp(date_tDBOutput_2));
								}
							} else {
								pstmt_tDBOutput_2.setNull(10, java.sql.Types.DATE);
							}

							pstmt_tDBOutput_2.addBatch();
							nb_line_tDBOutput_2++;

							batchSizeCounter_tDBOutput_2++;
							if (batchSize_tDBOutput_2 <= batchSizeCounter_tDBOutput_2) {
								try {
									int countSum_tDBOutput_2 = 0;
									for (int countEach_tDBOutput_2 : pstmt_tDBOutput_2.executeBatch()) {
										countSum_tDBOutput_2 += (countEach_tDBOutput_2 == java.sql.Statement.EXECUTE_FAILED
												? 0
												: 1);
									}
									rowsToCommitCount_tDBOutput_2 += countSum_tDBOutput_2;
									insertedCount_tDBOutput_2 += countSum_tDBOutput_2;
								} catch (java.sql.BatchUpdateException e) {
									globalMap.put("tDBOutput_2_ERROR_MESSAGE", e.getMessage());
									int countSum_tDBOutput_2 = 0;
									for (int countEach_tDBOutput_2 : e.getUpdateCounts()) {
										countSum_tDBOutput_2 += (countEach_tDBOutput_2 < 0 ? 0 : countEach_tDBOutput_2);
									}
									rowsToCommitCount_tDBOutput_2 += countSum_tDBOutput_2;
									insertedCount_tDBOutput_2 += countSum_tDBOutput_2;
									System.err.println(e.getMessage());
								}

								batchSizeCounter_tDBOutput_2 = 0;
							}
							commitCounter_tDBOutput_2++;

							if (commitEvery_tDBOutput_2 <= commitCounter_tDBOutput_2) {

								try {
									int countSum_tDBOutput_2 = 0;
									for (int countEach_tDBOutput_2 : pstmt_tDBOutput_2.executeBatch()) {
										countSum_tDBOutput_2 += (countEach_tDBOutput_2 < 0 ? 0 : 1);
									}
									rowsToCommitCount_tDBOutput_2 += countSum_tDBOutput_2;
									insertedCount_tDBOutput_2 += countSum_tDBOutput_2;
								} catch (java.sql.BatchUpdateException e) {
									globalMap.put("tDBOutput_2_ERROR_MESSAGE", e.getMessage());
									int countSum_tDBOutput_2 = 0;
									for (int countEach_tDBOutput_2 : e.getUpdateCounts()) {
										countSum_tDBOutput_2 += (countEach_tDBOutput_2 < 0 ? 0 : countEach_tDBOutput_2);
									}
									rowsToCommitCount_tDBOutput_2 += countSum_tDBOutput_2;
									insertedCount_tDBOutput_2 += countSum_tDBOutput_2;
									System.err.println(e.getMessage());

								}
								if (rowsToCommitCount_tDBOutput_2 != 0) {
								}
								conn_tDBOutput_2.commit();
								if (rowsToCommitCount_tDBOutput_2 != 0) {
									rowsToCommitCount_tDBOutput_2 = 0;
								}
								commitCounter_tDBOutput_2 = 0;

							}

							tos_count_tDBOutput_2++;

							/**
							 * [tDBOutput_2 main ] stop
							 */

							/**
							 * [tDBOutput_2 process_data_begin ] start
							 */

							currentComponent = "tDBOutput_2";

							/**
							 * [tDBOutput_2 process_data_begin ] stop
							 */

							/**
							 * [tDBOutput_2 process_data_end ] start
							 */

							currentComponent = "tDBOutput_2";

							/**
							 * [tDBOutput_2 process_data_end ] stop
							 */

						} // End of branch "CUSTOMER_DIM"

						/**
						 * [tMap_1 process_data_end ] start
						 */

						currentComponent = "tMap_1";

						/**
						 * [tMap_1 process_data_end ] stop
						 */

						/**
						 * [tDBInput_1 process_data_end ] start
						 */

						currentComponent = "tDBInput_1";

						/**
						 * [tDBInput_1 process_data_end ] stop
						 */

						/**
						 * [tDBInput_1 end ] start
						 */

						currentComponent = "tDBInput_1";

					}
				} finally {
					if (rs_tDBInput_1 != null) {
						rs_tDBInput_1.close();
					}
					if (stmt_tDBInput_1 != null) {
						stmt_tDBInput_1.close();
					}
					if (conn_tDBInput_1 != null && !conn_tDBInput_1.isClosed()) {

						conn_tDBInput_1.close();

						if ("com.mysql.cj.jdbc.Driver".equals((String) globalMap.get("driverClass_"))
								&& routines.system.BundleUtils.inOSGi()) {
							Class.forName("com.mysql.cj.jdbc.AbandonedConnectionCleanupThread")
									.getMethod("checkedShutdown").invoke(null, (Object[]) null);
						}

					}
				}
				globalMap.put("tDBInput_1_NB_LINE", nb_line_tDBInput_1);

				ok_Hash.put("tDBInput_1", true);
				end_Hash.put("tDBInput_1", System.currentTimeMillis());

				/**
				 * [tDBInput_1 end ] stop
				 */

				/**
				 * [tMap_1 end ] start
				 */

				currentComponent = "tMap_1";

// ###############################
// # Lookup hashes releasing
				if (tHash_Lookup_CUSTOMER_Type != null) {
					tHash_Lookup_CUSTOMER_Type.endGet();
				}
				globalMap.remove("tHash_Lookup_CUSTOMER_Type");

// ###############################      

				if (execStat) {
					runStat.updateStat(resourceMap, iterateId, 2, 0, "CUSTOMER");
				}

				ok_Hash.put("tMap_1", true);
				end_Hash.put("tMap_1", System.currentTimeMillis());

				/**
				 * [tMap_1 end ] stop
				 */

				/**
				 * [tDBOutput_2 end ] start
				 */

				currentComponent = "tDBOutput_2";

				try {
					if (batchSizeCounter_tDBOutput_2 != 0) {
						int countSum_tDBOutput_2 = 0;

						for (int countEach_tDBOutput_2 : pstmt_tDBOutput_2.executeBatch()) {
							countSum_tDBOutput_2 += (countEach_tDBOutput_2 == java.sql.Statement.EXECUTE_FAILED ? 0
									: 1);
						}
						rowsToCommitCount_tDBOutput_2 += countSum_tDBOutput_2;

						insertedCount_tDBOutput_2 += countSum_tDBOutput_2;

					}

				} catch (java.sql.BatchUpdateException e) {
					globalMap.put(currentComponent + "_ERROR_MESSAGE", e.getMessage());

					int countSum_tDBOutput_2 = 0;
					for (int countEach_tDBOutput_2 : e.getUpdateCounts()) {
						countSum_tDBOutput_2 += (countEach_tDBOutput_2 < 0 ? 0 : countEach_tDBOutput_2);
					}
					rowsToCommitCount_tDBOutput_2 += countSum_tDBOutput_2;

					insertedCount_tDBOutput_2 += countSum_tDBOutput_2;

					System.err.println(e.getMessage());

				}
				batchSizeCounter_tDBOutput_2 = 0;

				if (pstmt_tDBOutput_2 != null) {

					pstmt_tDBOutput_2.close();
					resourceMap.remove("pstmt_tDBOutput_2");

				}
				resourceMap.put("statementClosed_tDBOutput_2", true);
				if (commitCounter_tDBOutput_2 > 0 && rowsToCommitCount_tDBOutput_2 != 0) {

				}
				conn_tDBOutput_2.commit();
				if (commitCounter_tDBOutput_2 > 0 && rowsToCommitCount_tDBOutput_2 != 0) {

					rowsToCommitCount_tDBOutput_2 = 0;
				}
				commitCounter_tDBOutput_2 = 0;

				conn_tDBOutput_2.close();

				resourceMap.put("finish_tDBOutput_2", true);

				nb_line_deleted_tDBOutput_2 = nb_line_deleted_tDBOutput_2 + deletedCount_tDBOutput_2;
				nb_line_update_tDBOutput_2 = nb_line_update_tDBOutput_2 + updatedCount_tDBOutput_2;
				nb_line_inserted_tDBOutput_2 = nb_line_inserted_tDBOutput_2 + insertedCount_tDBOutput_2;
				nb_line_rejected_tDBOutput_2 = nb_line_rejected_tDBOutput_2 + rejectedCount_tDBOutput_2;

				globalMap.put("tDBOutput_2_NB_LINE", nb_line_tDBOutput_2);
				globalMap.put("tDBOutput_2_NB_LINE_UPDATED", nb_line_update_tDBOutput_2);
				globalMap.put("tDBOutput_2_NB_LINE_INSERTED", nb_line_inserted_tDBOutput_2);
				globalMap.put("tDBOutput_2_NB_LINE_DELETED", nb_line_deleted_tDBOutput_2);
				globalMap.put("tDBOutput_2_NB_LINE_REJECTED", nb_line_rejected_tDBOutput_2);

				if (execStat) {
					runStat.updateStat(resourceMap, iterateId, 2, 0, "CUSTOMER_DIM");
				}

				ok_Hash.put("tDBOutput_2", true);
				end_Hash.put("tDBOutput_2", System.currentTimeMillis());

				/**
				 * [tDBOutput_2 end ] stop
				 */

			} // end the resume

		} catch (java.lang.Exception e) {

			TalendException te = new TalendException(e, currentComponent, globalMap);

			throw te;
		} catch (java.lang.Error error) {

			runStat.stopThreadStat();

			throw error;
		} finally {

			// free memory for "tMap_1"
			globalMap.remove("tHash_Lookup_CUSTOMER_Type");

			try {

				/**
				 * [tDBInput_1 finally ] start
				 */

				currentComponent = "tDBInput_1";

				/**
				 * [tDBInput_1 finally ] stop
				 */

				/**
				 * [tMap_1 finally ] start
				 */

				currentComponent = "tMap_1";

				/**
				 * [tMap_1 finally ] stop
				 */

				/**
				 * [tDBOutput_2 finally ] start
				 */

				currentComponent = "tDBOutput_2";

				try {
					if (resourceMap.get("statementClosed_tDBOutput_2") == null) {
						java.sql.PreparedStatement pstmtToClose_tDBOutput_2 = null;
						if ((pstmtToClose_tDBOutput_2 = (java.sql.PreparedStatement) resourceMap
								.remove("pstmt_tDBOutput_2")) != null) {
							pstmtToClose_tDBOutput_2.close();
						}
					}
				} finally {
					if (resourceMap.get("finish_tDBOutput_2") == null) {
						java.sql.Connection ctn_tDBOutput_2 = null;
						if ((ctn_tDBOutput_2 = (java.sql.Connection) resourceMap.get("conn_tDBOutput_2")) != null) {
							try {
								ctn_tDBOutput_2.close();
							} catch (java.sql.SQLException sqlEx_tDBOutput_2) {
								String errorMessage_tDBOutput_2 = "failed to close the connection in tDBOutput_2 :"
										+ sqlEx_tDBOutput_2.getMessage();
								System.err.println(errorMessage_tDBOutput_2);
							}
						}
					}
				}

				/**
				 * [tDBOutput_2 finally ] stop
				 */

			} catch (java.lang.Exception e) {
				// ignore
			} catch (java.lang.Error error) {
				// ignore
			}
			resourceMap = null;
		}

		globalMap.put("tDBInput_1_SUBPROCESS_STATE", 1);
	}

	public static class CUSTOMER_TypeStruct
			implements routines.system.IPersistableComparableLookupRow<CUSTOMER_TypeStruct> {
		final static byte[] commonByteArrayLock_FIRST_orion = new byte[0];
		static byte[] commonByteArray_FIRST_orion = new byte[0];
		protected static final int DEFAULT_HASHCODE = 1;
		protected static final int PRIME = 31;
		protected int hashCode = DEFAULT_HASHCODE;
		public boolean hashCodeDirty = true;

		public String loopKey;

		public Double CUSTOMER_TYPE_ID;

		public Double getCUSTOMER_TYPE_ID() {
			return this.CUSTOMER_TYPE_ID;
		}

		public String CUSTOMER_TYPE;

		public String getCUSTOMER_TYPE() {
			return this.CUSTOMER_TYPE;
		}

		public Double CUSTOMER_GROUP_ID;

		public Double getCUSTOMER_GROUP_ID() {
			return this.CUSTOMER_GROUP_ID;
		}

		public String CUSTOMER_GROUP;

		public String getCUSTOMER_GROUP() {
			return this.CUSTOMER_GROUP;
		}

		@Override
		public int hashCode() {
			if (this.hashCodeDirty) {
				final int prime = PRIME;
				int result = DEFAULT_HASHCODE;

				result = prime * result + ((this.CUSTOMER_TYPE_ID == null) ? 0 : this.CUSTOMER_TYPE_ID.hashCode());

				this.hashCode = result;
				this.hashCodeDirty = false;
			}
			return this.hashCode;
		}

		@Override
		public boolean equals(Object obj) {
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			final CUSTOMER_TypeStruct other = (CUSTOMER_TypeStruct) obj;

			if (this.CUSTOMER_TYPE_ID == null) {
				if (other.CUSTOMER_TYPE_ID != null)
					return false;

			} else if (!this.CUSTOMER_TYPE_ID.equals(other.CUSTOMER_TYPE_ID))

				return false;

			return true;
		}

		public void copyDataTo(CUSTOMER_TypeStruct other) {

			other.CUSTOMER_TYPE_ID = this.CUSTOMER_TYPE_ID;
			other.CUSTOMER_TYPE = this.CUSTOMER_TYPE;
			other.CUSTOMER_GROUP_ID = this.CUSTOMER_GROUP_ID;
			other.CUSTOMER_GROUP = this.CUSTOMER_GROUP;

		}

		public void copyKeysDataTo(CUSTOMER_TypeStruct other) {

			other.CUSTOMER_TYPE_ID = this.CUSTOMER_TYPE_ID;

		}

		private String readString(DataInputStream dis, ObjectInputStream ois) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				byte[] byteArray = new byte[length];
				dis.read(byteArray);
				strReturn = new String(byteArray, utf8Charset);
			}
			return strReturn;
		}

		private String readString(DataInputStream dis, org.jboss.marshalling.Unmarshaller unmarshaller)
				throws IOException {
			String strReturn = null;
			int length = 0;
			length = unmarshaller.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				byte[] byteArray = new byte[length];
				unmarshaller.read(byteArray);
				strReturn = new String(byteArray, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, DataOutputStream dos, org.jboss.marshalling.Marshaller marshaller)
				throws IOException {
			if (str == null) {
				marshaller.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				marshaller.writeInt(byteArray.length);
				marshaller.write(byteArray);
			}
		}

		private void writeString(String str, DataOutputStream dos, ObjectOutputStream oos) throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		public void readKeysData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_FIRST_orion) {

				try {

					int length = 0;

					length = dis.readByte();
					if (length == -1) {
						this.CUSTOMER_TYPE_ID = null;
					} else {
						this.CUSTOMER_TYPE_ID = dis.readDouble();
					}

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void readKeysData(org.jboss.marshalling.Unmarshaller dis) {

			synchronized (commonByteArrayLock_FIRST_orion) {

				try {

					int length = 0;

					length = dis.readByte();
					if (length == -1) {
						this.CUSTOMER_TYPE_ID = null;
					} else {
						this.CUSTOMER_TYPE_ID = dis.readDouble();
					}

				} catch (IOException e) {
					throw new RuntimeException(e);

				}

			}

		}

		public void writeKeysData(ObjectOutputStream dos) {
			try {

				// Double

				if (this.CUSTOMER_TYPE_ID == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeDouble(this.CUSTOMER_TYPE_ID);
				}

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public void writeKeysData(org.jboss.marshalling.Marshaller dos) {
			try {

				// Double

				if (this.CUSTOMER_TYPE_ID == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeDouble(this.CUSTOMER_TYPE_ID);
				}

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		/**
		 * Fill Values data by reading ObjectInputStream.
		 */
		public void readValuesData(DataInputStream dis, ObjectInputStream ois) {
			try {

				int length = 0;

				this.CUSTOMER_TYPE = readString(dis, ois);

				length = dis.readByte();
				if (length == -1) {
					this.CUSTOMER_GROUP_ID = null;
				} else {
					this.CUSTOMER_GROUP_ID = dis.readDouble();
				}

				this.CUSTOMER_GROUP = readString(dis, ois);

			} catch (IOException e) {
				throw new RuntimeException(e);

			}

		}

		public void readValuesData(DataInputStream dis, org.jboss.marshalling.Unmarshaller objectIn) {
			try {
				int length = 0;

				this.CUSTOMER_TYPE = readString(dis, objectIn);

				length = objectIn.readByte();
				if (length == -1) {
					this.CUSTOMER_GROUP_ID = null;
				} else {
					this.CUSTOMER_GROUP_ID = objectIn.readDouble();
				}

				this.CUSTOMER_GROUP = readString(dis, objectIn);

			} catch (IOException e) {
				throw new RuntimeException(e);

			}

		}

		/**
		 * Return a byte array which represents Values data.
		 */
		public void writeValuesData(DataOutputStream dos, ObjectOutputStream oos) {
			try {

				writeString(this.CUSTOMER_TYPE, dos, oos);

				if (this.CUSTOMER_GROUP_ID == null) {
					dos.writeByte(-1);
				} else {
					dos.writeByte(0);
					dos.writeDouble(this.CUSTOMER_GROUP_ID);
				}

				writeString(this.CUSTOMER_GROUP, dos, oos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public void writeValuesData(DataOutputStream dos, org.jboss.marshalling.Marshaller objectOut) {
			try {

				writeString(this.CUSTOMER_TYPE, dos, objectOut);

				if (this.CUSTOMER_GROUP_ID == null) {
					objectOut.writeByte(-1);
				} else {
					objectOut.writeByte(0);
					objectOut.writeDouble(this.CUSTOMER_GROUP_ID);
				}

				writeString(this.CUSTOMER_GROUP, dos, objectOut);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}
		}

		public boolean supportMarshaller() {
			return true;
		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("CUSTOMER_TYPE_ID=" + String.valueOf(CUSTOMER_TYPE_ID));
			sb.append(",CUSTOMER_TYPE=" + CUSTOMER_TYPE);
			sb.append(",CUSTOMER_GROUP_ID=" + String.valueOf(CUSTOMER_GROUP_ID));
			sb.append(",CUSTOMER_GROUP=" + CUSTOMER_GROUP);
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(CUSTOMER_TypeStruct other) {

			int returnValue = -1;

			returnValue = checkNullsAndCompare(this.CUSTOMER_TYPE_ID, other.CUSTOMER_TYPE_ID);
			if (returnValue != 0) {
				return returnValue;
			}

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(), object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public void tDBInput_2Process(final java.util.Map<String, Object> globalMap) throws TalendException {
		globalMap.put("tDBInput_2_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";

		String currentComponent = "";
		java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

		try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { // start the resume
				globalResumeTicket = true;

				CUSTOMER_TypeStruct CUSTOMER_Type = new CUSTOMER_TypeStruct();

				/**
				 * [tAdvancedHash_CUSTOMER_Type begin ] start
				 */

				ok_Hash.put("tAdvancedHash_CUSTOMER_Type", false);
				start_Hash.put("tAdvancedHash_CUSTOMER_Type", System.currentTimeMillis());

				currentComponent = "tAdvancedHash_CUSTOMER_Type";

				if (execStat) {
					runStat.updateStatOnConnection(resourceMap, iterateId, 0, 0, "CUSTOMER_Type");
				}

				int tos_count_tAdvancedHash_CUSTOMER_Type = 0;

				// connection name:CUSTOMER_Type
				// source node:tDBInput_2 - inputs:(after_tDBInput_1)
				// outputs:(CUSTOMER_Type,CUSTOMER_Type) | target
				// node:tAdvancedHash_CUSTOMER_Type - inputs:(CUSTOMER_Type) outputs:()
				// linked node: tMap_1 - inputs:(CUSTOMER,CUSTOMER_Type) outputs:(CUSTOMER_DIM)

				org.talend.designer.components.lookup.common.ICommonLookup.MATCHING_MODE matchingModeEnum_CUSTOMER_Type = org.talend.designer.components.lookup.common.ICommonLookup.MATCHING_MODE.UNIQUE_MATCH;

				org.talend.designer.components.lookup.memory.AdvancedMemoryLookup<CUSTOMER_TypeStruct> tHash_Lookup_CUSTOMER_Type = org.talend.designer.components.lookup.memory.AdvancedMemoryLookup
						.<CUSTOMER_TypeStruct>getLookup(matchingModeEnum_CUSTOMER_Type);

				globalMap.put("tHash_Lookup_CUSTOMER_Type", tHash_Lookup_CUSTOMER_Type);

				/**
				 * [tAdvancedHash_CUSTOMER_Type begin ] stop
				 */

				/**
				 * [tDBInput_2 begin ] start
				 */

				ok_Hash.put("tDBInput_2", false);
				start_Hash.put("tDBInput_2", System.currentTimeMillis());

				currentComponent = "tDBInput_2";

				int tos_count_tDBInput_2 = 0;

				int nb_line_tDBInput_2 = 0;
				java.sql.Connection conn_tDBInput_2 = null;
				String driverClass_tDBInput_2 = "net.ucanaccess.jdbc.UcanaccessDriver";
				java.lang.Class.forName(driverClass_tDBInput_2);

				String url_tDBInput_2 = "jdbc:ucanaccess://" + "C:/Users/bechi/Downloads/orion.mdb"
						+ ";jackcessOpener=org.talend.ucanaccess.encrypt.CryptCodecOpener;singleConnection=true";
				String dbUser_tDBInput_2 = "";

				final String decryptedPassword_tDBInput_2 = routines.system.PasswordEncryptUtil
						.decryptPassword("enc:routine.encryption.key.v1:IgNcmHy+tr/8D3vrbiWABmbvQeJCoFs/lEXt5Q==");

				String dbPwd_tDBInput_2 = decryptedPassword_tDBInput_2;

				String atnParams_tDBInput_2 = "jackcessOpener=org.talend.ucanaccess.encrypt.CryptCodecOpener;memory=false";
				atnParams_tDBInput_2 = atnParams_tDBInput_2.replaceAll("&", "\n");
				java.util.Properties atnParamsPrope_tDBInput_2 = new java.util.Properties();
				atnParamsPrope_tDBInput_2.put("user", dbUser_tDBInput_2);
				atnParamsPrope_tDBInput_2.put("password", dbPwd_tDBInput_2);
				atnParamsPrope_tDBInput_2.load(new java.io.ByteArrayInputStream(atnParams_tDBInput_2.getBytes()));
				conn_tDBInput_2 = java.sql.DriverManager.getConnection(url_tDBInput_2, atnParamsPrope_tDBInput_2);

				java.sql.Statement stmt_tDBInput_2 = conn_tDBInput_2.createStatement();

				String dbquery_tDBInput_2 = "SELECT \n  CUSTOMER_TYPE.CUSTOMER_TYPE_ID, \n  CUSTOMER_TYPE.CUSTOMER_TYPE, \n  CUSTOMER_TYPE.CUSTOMER_GROUP_ID, \n  CUSTOM"
						+ "ER_TYPE.CUSTOMER_GROUP\nFROM CUSTOMER_TYPE";

				globalMap.put("tDBInput_2_QUERY", dbquery_tDBInput_2);
				java.sql.ResultSet rs_tDBInput_2 = null;

				try {
					rs_tDBInput_2 = stmt_tDBInput_2.executeQuery(dbquery_tDBInput_2);
					java.sql.ResultSetMetaData rsmd_tDBInput_2 = rs_tDBInput_2.getMetaData();
					int colQtyInRs_tDBInput_2 = rsmd_tDBInput_2.getColumnCount();

					String tmpContent_tDBInput_2 = null;

					while (rs_tDBInput_2.next()) {
						nb_line_tDBInput_2++;

						if (colQtyInRs_tDBInput_2 < 1) {
							CUSTOMER_Type.CUSTOMER_TYPE_ID = null;
						} else {

							CUSTOMER_Type.CUSTOMER_TYPE_ID = rs_tDBInput_2.getDouble(1);
							if (rs_tDBInput_2.wasNull()) {
								CUSTOMER_Type.CUSTOMER_TYPE_ID = null;
							}
						}
						if (colQtyInRs_tDBInput_2 < 2) {
							CUSTOMER_Type.CUSTOMER_TYPE = null;
						} else {

							CUSTOMER_Type.CUSTOMER_TYPE = routines.system.JDBCUtil.getString(rs_tDBInput_2, 2, false);
						}
						if (colQtyInRs_tDBInput_2 < 3) {
							CUSTOMER_Type.CUSTOMER_GROUP_ID = null;
						} else {

							CUSTOMER_Type.CUSTOMER_GROUP_ID = rs_tDBInput_2.getDouble(3);
							if (rs_tDBInput_2.wasNull()) {
								CUSTOMER_Type.CUSTOMER_GROUP_ID = null;
							}
						}
						if (colQtyInRs_tDBInput_2 < 4) {
							CUSTOMER_Type.CUSTOMER_GROUP = null;
						} else {

							CUSTOMER_Type.CUSTOMER_GROUP = routines.system.JDBCUtil.getString(rs_tDBInput_2, 4, false);
						}

						/**
						 * [tDBInput_2 begin ] stop
						 */

						/**
						 * [tDBInput_2 main ] start
						 */

						currentComponent = "tDBInput_2";

						tos_count_tDBInput_2++;

						/**
						 * [tDBInput_2 main ] stop
						 */

						/**
						 * [tDBInput_2 process_data_begin ] start
						 */

						currentComponent = "tDBInput_2";

						/**
						 * [tDBInput_2 process_data_begin ] stop
						 */

						/**
						 * [tAdvancedHash_CUSTOMER_Type main ] start
						 */

						currentComponent = "tAdvancedHash_CUSTOMER_Type";

						if (execStat) {
							runStat.updateStatOnConnection(iterateId, 1, 1

									, "CUSTOMER_Type"

							);
						}

						CUSTOMER_TypeStruct CUSTOMER_Type_HashRow = new CUSTOMER_TypeStruct();

						CUSTOMER_Type_HashRow.CUSTOMER_TYPE_ID = CUSTOMER_Type.CUSTOMER_TYPE_ID;

						CUSTOMER_Type_HashRow.CUSTOMER_TYPE = CUSTOMER_Type.CUSTOMER_TYPE;

						CUSTOMER_Type_HashRow.CUSTOMER_GROUP_ID = CUSTOMER_Type.CUSTOMER_GROUP_ID;

						CUSTOMER_Type_HashRow.CUSTOMER_GROUP = CUSTOMER_Type.CUSTOMER_GROUP;

						tHash_Lookup_CUSTOMER_Type.put(CUSTOMER_Type_HashRow);

						tos_count_tAdvancedHash_CUSTOMER_Type++;

						/**
						 * [tAdvancedHash_CUSTOMER_Type main ] stop
						 */

						/**
						 * [tAdvancedHash_CUSTOMER_Type process_data_begin ] start
						 */

						currentComponent = "tAdvancedHash_CUSTOMER_Type";

						/**
						 * [tAdvancedHash_CUSTOMER_Type process_data_begin ] stop
						 */

						/**
						 * [tAdvancedHash_CUSTOMER_Type process_data_end ] start
						 */

						currentComponent = "tAdvancedHash_CUSTOMER_Type";

						/**
						 * [tAdvancedHash_CUSTOMER_Type process_data_end ] stop
						 */

						/**
						 * [tDBInput_2 process_data_end ] start
						 */

						currentComponent = "tDBInput_2";

						/**
						 * [tDBInput_2 process_data_end ] stop
						 */

						/**
						 * [tDBInput_2 end ] start
						 */

						currentComponent = "tDBInput_2";

					}
				} finally {
					if (rs_tDBInput_2 != null) {
						rs_tDBInput_2.close();
					}
					if (stmt_tDBInput_2 != null) {
						stmt_tDBInput_2.close();
					}
					if (conn_tDBInput_2 != null && !conn_tDBInput_2.isClosed()) {

						conn_tDBInput_2.close();

						if ("com.mysql.cj.jdbc.Driver".equals((String) globalMap.get("driverClass_"))
								&& routines.system.BundleUtils.inOSGi()) {
							Class.forName("com.mysql.cj.jdbc.AbandonedConnectionCleanupThread")
									.getMethod("checkedShutdown").invoke(null, (Object[]) null);
						}

					}
				}
				globalMap.put("tDBInput_2_NB_LINE", nb_line_tDBInput_2);

				ok_Hash.put("tDBInput_2", true);
				end_Hash.put("tDBInput_2", System.currentTimeMillis());

				/**
				 * [tDBInput_2 end ] stop
				 */

				/**
				 * [tAdvancedHash_CUSTOMER_Type end ] start
				 */

				currentComponent = "tAdvancedHash_CUSTOMER_Type";

				tHash_Lookup_CUSTOMER_Type.endPut();

				if (execStat) {
					runStat.updateStat(resourceMap, iterateId, 2, 0, "CUSTOMER_Type");
				}

				ok_Hash.put("tAdvancedHash_CUSTOMER_Type", true);
				end_Hash.put("tAdvancedHash_CUSTOMER_Type", System.currentTimeMillis());

				/**
				 * [tAdvancedHash_CUSTOMER_Type end ] stop
				 */

			} // end the resume

		} catch (java.lang.Exception e) {

			TalendException te = new TalendException(e, currentComponent, globalMap);

			throw te;
		} catch (java.lang.Error error) {

			runStat.stopThreadStat();

			throw error;
		} finally {

			try {

				/**
				 * [tDBInput_2 finally ] start
				 */

				currentComponent = "tDBInput_2";

				/**
				 * [tDBInput_2 finally ] stop
				 */

				/**
				 * [tAdvancedHash_CUSTOMER_Type finally ] start
				 */

				currentComponent = "tAdvancedHash_CUSTOMER_Type";

				/**
				 * [tAdvancedHash_CUSTOMER_Type finally ] stop
				 */

			} catch (java.lang.Exception e) {
				// ignore
			} catch (java.lang.Error error) {
				// ignore
			}
			resourceMap = null;
		}

		globalMap.put("tDBInput_2_SUBPROCESS_STATE", 1);
	}

	public String resuming_logs_dir_path = null;
	public String resuming_checkpoint_path = null;
	public String parent_part_launcher = null;
	private String resumeEntryMethodName = null;
	private boolean globalResumeTicket = false;

	public boolean watch = false;
	// portStats is null, it means don't execute the statistics
	public Integer portStats = null;
	public int portTraces = 4334;
	public String clientHost;
	public String defaultClientHost = "localhost";
	public String contextStr = "Default";
	public boolean isDefaultContext = true;
	public String pid = "0";
	public String rootPid = null;
	public String fatherPid = null;
	public String fatherNode = null;
	public long startTime = 0;
	public boolean isChildJob = false;
	public String log4jLevel = "";

	private boolean enableLogStash;

	private boolean execStat = true;

	private ThreadLocal<java.util.Map<String, String>> threadLocal = new ThreadLocal<java.util.Map<String, String>>() {
		protected java.util.Map<String, String> initialValue() {
			java.util.Map<String, String> threadRunResultMap = new java.util.HashMap<String, String>();
			threadRunResultMap.put("errorCode", null);
			threadRunResultMap.put("status", "");
			return threadRunResultMap;
		};
	};

	protected PropertiesWithType context_param = new PropertiesWithType();
	public java.util.Map<String, Object> parentContextMap = new java.util.HashMap<String, Object>();

	public String status = "";

	public static void main(String[] args) {
		final orion orionClass = new orion();

		int exitCode = orionClass.runJobInTOS(args);

		System.exit(exitCode);
	}

	public String[][] runJob(String[] args) {

		int exitCode = runJobInTOS(args);
		String[][] bufferValue = new String[][] { { Integer.toString(exitCode) } };

		return bufferValue;
	}

	public boolean hastBufferOutputComponent() {
		boolean hastBufferOutput = false;

		return hastBufferOutput;
	}

	public int runJobInTOS(String[] args) {
		// reset status
		status = "";

		String lastStr = "";
		for (String arg : args) {
			if (arg.equalsIgnoreCase("--context_param")) {
				lastStr = arg;
			} else if (lastStr.equals("")) {
				evalParam(arg);
			} else {
				evalParam(lastStr + " " + arg);
				lastStr = "";
			}
		}
		enableLogStash = "true".equalsIgnoreCase(System.getProperty("audit.enabled"));

		if (clientHost == null) {
			clientHost = defaultClientHost;
		}

		if (pid == null || "0".equals(pid)) {
			pid = TalendString.getAsciiRandomString(6);
		}

		if (rootPid == null) {
			rootPid = pid;
		}
		if (fatherPid == null) {
			fatherPid = pid;
		} else {
			isChildJob = true;
		}

		if (portStats != null) {
			// portStats = -1; //for testing
			if (portStats < 0 || portStats > 65535) {
				// issue:10869, the portStats is invalid, so this client socket can't open
				System.err.println("The statistics socket port " + portStats + " is invalid.");
				execStat = false;
			}
		} else {
			execStat = false;
		}
		boolean inOSGi = routines.system.BundleUtils.inOSGi();

		if (inOSGi) {
			java.util.Dictionary<String, Object> jobProperties = routines.system.BundleUtils.getJobProperties(jobName);

			if (jobProperties != null && jobProperties.get("context") != null) {
				contextStr = (String) jobProperties.get("context");
			}
		}

		try {
			// call job/subjob with an existing context, like: --context=production. if
			// without this parameter, there will use the default context instead.
			java.io.InputStream inContext = orion.class.getClassLoader()
					.getResourceAsStream("first/orion_0_1/contexts/" + contextStr + ".properties");
			if (inContext == null) {
				inContext = orion.class.getClassLoader()
						.getResourceAsStream("config/contexts/" + contextStr + ".properties");
			}
			if (inContext != null) {
				try {
					// defaultProps is in order to keep the original context value
					if (context != null && context.isEmpty()) {
						defaultProps.load(inContext);
						context = new ContextProperties(defaultProps);
					}
				} finally {
					inContext.close();
				}
			} else if (!isDefaultContext) {
				// print info and job continue to run, for case: context_param is not empty.
				System.err.println("Could not find the context " + contextStr);
			}

			if (!context_param.isEmpty()) {
				context.putAll(context_param);
				// set types for params from parentJobs
				for (Object key : context_param.keySet()) {
					String context_key = key.toString();
					String context_type = context_param.getContextType(context_key);
					context.setContextType(context_key, context_type);

				}
			}
			class ContextProcessing {
				private void processContext_0() {
				}

				public void processAllContext() {
					processContext_0();
				}
			}

			new ContextProcessing().processAllContext();
		} catch (java.io.IOException ie) {
			System.err.println("Could not load context " + contextStr);
			ie.printStackTrace();
		}

		// get context value from parent directly
		if (parentContextMap != null && !parentContextMap.isEmpty()) {
		}

		// Resume: init the resumeUtil
		resumeEntryMethodName = ResumeUtil.getResumeEntryMethodName(resuming_checkpoint_path);
		resumeUtil = new ResumeUtil(resuming_logs_dir_path, isChildJob, rootPid);
		resumeUtil.initCommonInfo(pid, rootPid, fatherPid, projectName, jobName, contextStr, jobVersion);

		List<String> parametersToEncrypt = new java.util.ArrayList<String>();
		// Resume: jobStart
		resumeUtil.addLog("JOB_STARTED", "JOB:" + jobName, parent_part_launcher, Thread.currentThread().getId() + "",
				"", "", "", "", resumeUtil.convertToJsonText(context, parametersToEncrypt));

		if (execStat) {
			try {
				runStat.openSocket(!isChildJob);
				runStat.setAllPID(rootPid, fatherPid, pid, jobName);
				runStat.startThreadStat(clientHost, portStats);
				runStat.updateStatOnJob(RunStat.JOBSTART, fatherNode);
			} catch (java.io.IOException ioException) {
				ioException.printStackTrace();
			}
		}

		java.util.concurrent.ConcurrentHashMap<Object, Object> concurrentHashMap = new java.util.concurrent.ConcurrentHashMap<Object, Object>();
		globalMap.put("concurrentHashMap", concurrentHashMap);

		long startUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
		long endUsedMemory = 0;
		long end = 0;

		startTime = System.currentTimeMillis();

		this.globalResumeTicket = true;// to run tPreJob

		this.globalResumeTicket = false;// to run others jobs

		try {
			errorCode = null;
			tDBInput_1Process(globalMap);
			if (!"failure".equals(status)) {
				status = "end";
			}
		} catch (TalendException e_tDBInput_1) {
			globalMap.put("tDBInput_1_SUBPROCESS_STATE", -1);

			e_tDBInput_1.printStackTrace();

		}

		this.globalResumeTicket = true;// to run tPostJob

		end = System.currentTimeMillis();

		if (watch) {
			System.out.println((end - startTime) + " milliseconds");
		}

		endUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
		if (false) {
			System.out.println((endUsedMemory - startUsedMemory) + " bytes memory increase when running : orion");
		}

		if (execStat) {
			runStat.updateStatOnJob(RunStat.JOBEND, fatherNode);
			runStat.stopThreadStat();
		}
		int returnCode = 0;

		if (errorCode == null) {
			returnCode = status != null && status.equals("failure") ? 1 : 0;
		} else {
			returnCode = errorCode.intValue();
		}
		resumeUtil.addLog("JOB_ENDED", "JOB:" + jobName, parent_part_launcher, Thread.currentThread().getId() + "", "",
				"" + returnCode, "", "", "");

		return returnCode;

	}

	// only for OSGi env
	public void destroy() {

	}

	private java.util.Map<String, Object> getSharedConnections4REST() {
		java.util.Map<String, Object> connections = new java.util.HashMap<String, Object>();

		return connections;
	}

	private void evalParam(String arg) {
		if (arg.startsWith("--resuming_logs_dir_path")) {
			resuming_logs_dir_path = arg.substring(25);
		} else if (arg.startsWith("--resuming_checkpoint_path")) {
			resuming_checkpoint_path = arg.substring(27);
		} else if (arg.startsWith("--parent_part_launcher")) {
			parent_part_launcher = arg.substring(23);
		} else if (arg.startsWith("--watch")) {
			watch = true;
		} else if (arg.startsWith("--stat_port=")) {
			String portStatsStr = arg.substring(12);
			if (portStatsStr != null && !portStatsStr.equals("null")) {
				portStats = Integer.parseInt(portStatsStr);
			}
		} else if (arg.startsWith("--trace_port=")) {
			portTraces = Integer.parseInt(arg.substring(13));
		} else if (arg.startsWith("--client_host=")) {
			clientHost = arg.substring(14);
		} else if (arg.startsWith("--context=")) {
			contextStr = arg.substring(10);
			isDefaultContext = false;
		} else if (arg.startsWith("--father_pid=")) {
			fatherPid = arg.substring(13);
		} else if (arg.startsWith("--root_pid=")) {
			rootPid = arg.substring(11);
		} else if (arg.startsWith("--father_node=")) {
			fatherNode = arg.substring(14);
		} else if (arg.startsWith("--pid=")) {
			pid = arg.substring(6);
		} else if (arg.startsWith("--context_type")) {
			String keyValue = arg.substring(15);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				if (fatherPid == null) {
					context_param.setContextType(keyValue.substring(0, index),
							replaceEscapeChars(keyValue.substring(index + 1)));
				} else { // the subjob won't escape the especial chars
					context_param.setContextType(keyValue.substring(0, index), keyValue.substring(index + 1));
				}

			}

		} else if (arg.startsWith("--context_param")) {
			String keyValue = arg.substring(16);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				if (fatherPid == null) {
					context_param.put(keyValue.substring(0, index), replaceEscapeChars(keyValue.substring(index + 1)));
				} else { // the subjob won't escape the especial chars
					context_param.put(keyValue.substring(0, index), keyValue.substring(index + 1));
				}
			}
		} else if (arg.startsWith("--log4jLevel=")) {
			log4jLevel = arg.substring(13);
		} else if (arg.startsWith("--audit.enabled") && arg.contains("=")) {// for trunjob call
			final int equal = arg.indexOf('=');
			final String key = arg.substring("--".length(), equal);
			System.setProperty(key, arg.substring(equal + 1));
		}
	}

	private static final String NULL_VALUE_EXPRESSION_IN_COMMAND_STRING_FOR_CHILD_JOB_ONLY = "<TALEND_NULL>";

	private final String[][] escapeChars = { { "\\\\", "\\" }, { "\\n", "\n" }, { "\\'", "\'" }, { "\\r", "\r" },
			{ "\\f", "\f" }, { "\\b", "\b" }, { "\\t", "\t" } };

	private String replaceEscapeChars(String keyValue) {

		if (keyValue == null || ("").equals(keyValue.trim())) {
			return keyValue;
		}

		StringBuilder result = new StringBuilder();
		int currIndex = 0;
		while (currIndex < keyValue.length()) {
			int index = -1;
			// judege if the left string includes escape chars
			for (String[] strArray : escapeChars) {
				index = keyValue.indexOf(strArray[0], currIndex);
				if (index >= 0) {

					result.append(keyValue.substring(currIndex, index + strArray[0].length()).replace(strArray[0],
							strArray[1]));
					currIndex = index + strArray[0].length();
					break;
				}
			}
			// if the left string doesn't include escape chars, append the left into the
			// result
			if (index < 0) {
				result.append(keyValue.substring(currIndex));
				currIndex = currIndex + keyValue.length();
			}
		}

		return result.toString();
	}

	public Integer getErrorCode() {
		return errorCode;
	}

	public String getStatus() {
		return status;
	}

	ResumeUtil resumeUtil = null;
}
/************************************************************************************************
 * 111478 characters generated by Talend Open Studio for Data Integration on the
 * January 31, 2024 at 10:44:44 AM CET
 ************************************************************************************************/